openapi: 3.0.0
info:
  title: Cars Manajement API
  version: 0.0.1
servers:
  - description: Local Server
    url: http://localhost:8000/
tags:
  - name: Cars
    description: Contain every operation about Cars Resource
paths:
  /api/v1/cars:
    get:
      operationId: getAllCars
      tags:
      - Cars
      responses:
        "200":
          description: responses success get all data cars
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: SUCCESS
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "SUCCESS"
                      message:
                        type: string
        "401":
          description: Response when accessing protected endpoint without access
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: FAIL
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "UNAUTHORIZED"
                      message:
                        type: string
                        example: "Access is not granted"
  /api/v1/insertCars:
    post:
      operationId: createCar
      tags:
      - Cars
      requestBody:
        $ref: "#/components/requestBodies/CarsRequest"
      responses:
        "200":
          $ref: "#/components/responses/PostResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedResponse"
        "403":
          $ref: "#/components/responses/ForbiddenResponse"


components:
  requestBodies:
      CarsRequest:
        description: Create Car Data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nama:
                  type: string
                  example: "BMW"
                harga:
                  type: integer
                  example: 200000
                ukuran:
                  type: string
                  example: "Small"
                gambar:
                  type: string
                  example: "bmw.jpg"
  responses:
      PostResponse:
            description: create data car success
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      example: SUCCESS
                    datas:
                      type: object
                      properties:
                        name:
                          type: string
                          example: "SUCCESS"
                        message:
                          type: string
                        data:
                          $ref: "#/components/schemas/Cars"
                          
      UnauthorizedResponse:
            description: Response when accessing protected endpoint without access
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      example: FAIL
                    data:
                      type: object
                      properties:
                        name:
                          type: string
                          example: "UNAUTHORIZED"
                        message:
                          type: string
                          example: "Access is not granted"
                          
      ForbiddenResponse:
            description: Response when accessing protected endpoint with access but sufficient access
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      example: FAIL
                    data:
                      type: object
                      properties:
                        name:
                          type: string
                          example: "FORBIDDEN"
                        message:
                          type: string
                          example: "Invalid access level"

  schemas:
    Cars:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nama:
          type: string
          example: BMW
        harga:
          type: integer
          example: 200000
        ukuran:
          type: string
          example: Small
        gambar:
          type: string
          example: mobil.jpg
        createdAt:
          type: string
          example: "2021-07-30 17:00:00 +0700"
        updatedAt:  
          type: string
          example: "2021-07-30 17:00:00 +0700"
